title: Yuanhong (Claire) Zhang

description: > 
   Claire' Data Science Projects Portfolio
   <br><br>
   Here you will find how I solve problems using Data and Analytics
   <br><br>
   <a href="https://www.linkedin.com/in/yuanhongzhang/">LinkedIn 


theme: jekyll-theme-minimal
