title: Yuanhong (Claire) Zhang

description: > 
   Claire' Data Science Projects Portfolio
   <br><br>
   Welcome to connect!
   <br><br>
   <a href="https://www.linkedin.com/in/yuanhongzhang/">LinkedIn 


theme: jekyll-theme-minimal
